### ISSUE TITLE
Locale not recognized (in date format) (?)

### ISSUE THREAD

**Issue by ptar** [Theophilix/event-table-edit#27] opened 2016-12-08 21:32 UTC
EventtableEdit 4.5 is used in a Joomla with German language installed.
I use date fields formatted as "%d.%m.%Y (KW %V)"
For entries in 2017, I saw misaligned calender week numbers. The misalignment is by one week and fits to the the difference between American and ISO week numbers for 2017.
I added %B to the format pattern, but the month names are in English. So my assumption is, that the locale is not correctly recognized by EventTableEdit.

**Comment by Theophilix** [comment] 2016-12-12 11:35
Thank you very much for reporting this bug. Any help in correcting this bug is apreciated.

**Comment by Theophilix** [comment] 2016-12-23 10:23
Hello ptar,
please check again with this version: [eventtableedit(21-12-2016).zip](https://github.com/Theophilix/event-table-edit/files/670603/eventtableedit.21-12-2016.zip) and tell if problem is solved.
Because I can't reproduce your error.

**Comment by ptar** [comment] 2017-01-04 12:55
Hello Theophilix,
thanks for the provided version!
And maybe you can't reproduce the error, because I have to say "**I'm sorry, my fault**": Almost all of the dates in the events are on Sundays and Jan. 1st 2017 is the first Sunday, but in Week 52 (of 2016). So maybe - because I had to deal with the US/ISO missalignment lately - I was just assuming, that it was an error ("selbsterfüllende Prophezeiung").
Nevertheless, with "%d.%m.%Y (KW %V) %B", the %B results in "January", not "Januar".
But this could be a general misconfiguration (I got the Joomla installation about 4 months ago "as is" and it's only providing German content).
Do you have an idea how to easily check if the locale is correctly provided in the rest of Joomla? Thanks!

**Comment by Theophilix** [comment] 2017-01-04 21:58
Thank you for your explanations. This is a bug. The locale can be defined via PHP: http://php.net/manual/de/function.setlocale.php. Check the follwing php file: %root%\site\helpers\etetable.php.
Solution: I will add a general LC_ALL setting and an additional locale - option to "style"-tab. But please be patient. This may take some weeks...

**Comment by ptar** [comment] 2017-01-12 20:51
Hello Theophilix,
thanks for fixing the locale bug!
And: I'll be patient :-)

**Comment by Theophilix** [comment] 2017-01-24 16:41
Fixed with 4.4.3 version.

**Closed as completed by Theophilix** 2017-01-24 16:41 UTC
Labels: bug
