### ISSUE TITLE
Frontend problems after updating to 4.8.6

### ISSUE THREAD

**Issue by andyarrigo** [Theophilix/event-table-edit#183] opened 2021-01-25 15:52 UTC
Hello,

i just updated my ETE extension on my joomla working on an internal xampp server...

I can't use anymore ETE, i get this two errror messages:
1. Notice: Undefined property: stdClass::$standardlayout in C:\xampp\apps\joomla\htdocs\plugins\content\loadete\templates\default_filter.php on line 15
2. Notice: Undefined property: stdClass::$standardlayout in C:\xampp\apps\joomla\htdocs\plugins\content\loadete\templates\default_table.php on line 29

I can see the ols table entries but i can't add new ones...add button is not showing anymore...can you help me solve this problems?

Kind regards

Andy

**Comment by Theophilix** [comment] 2021-01-25 22:51
I can't reproduce this error. Did you try to backup your tables via xml or csv export and uninstall and reinstall ETE completely?
Are all ACL settings (rights/roles/security settings) ok?

**Comment by andyarrigo** [comment] 2021-01-26 16:04
I reinstalled completely my xamp, joomla and ETE...with a fresh installation is almost working but...
1. With release 4.8.6 there is no way to create a new normal form...rows and cells amount boxes are completely missing...so uninstalkled again and installed a previous 4.7.7 version...result: Working!

**Comment by andyarrigo** [comment] 2021-01-26 16:06
2. CSV Tables export and Import: The date is not exporting correctly...instead the correct date i get everywhere 01.01.1970!! Tryed xml export and import and get an unknown error...so its impossible to get the data back trough an export...CAn i copy the tables from MYSQL DB? Which tables contains just the data and not other settings?

**Comment by Theophilix** [comment] 2021-01-27 14:03
You could try xml export instead, with all values. Do you get the same date error?
The "create a new form"-bug is well known https://github.com/Theophilix/event-table-edit/issues/182. It will be fixed soon.
Could you please upload your anonymised csv, so I can check? Perhaps there are some strange characters / values in your table data. Try to upload my csv testfile: [Demo table normal.zip](https://github.com/Theophilix/event-table-edit/files/5880743/Demo.table.normal.zip)
Data is stored in [name of database]_eventtableedit_rows_1  or _eventtableedit_rows_2  or *4 or 5 depending on your number of tables.

**Comment by Theophilix** [comment] 2021-07-02 16:06
Fixed in 4.8.8 version.

**Closed as completed by Theophilix** 2021-07-02 16:06 UTC
